apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice-go
  template:
    metadata:
      labels:
        app: inventoryservice-go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "inventoryservice-go"
        dapr.io/app-port: "8081"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
        - name: inventoryservice-go
          image: localhost:5000/inventoryservice-go:v1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice-go
spec:
  selector:
    app: inventoryservice-go
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
