apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice-go
  template:
    metadata:
      labels:
        app: orderservice-go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderservice-go"
        dapr.io/app-port: "8080"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
        - name: orderservice-go
          image: localhost:5000/orderservice-go:v1.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-go
spec:
  selector:
    app: orderservice-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
