apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  # Example:
  # conn: "host=postgres.default.svc.cluster.local user=postgres password=postgres dbname=dapr sslmode=disable"
  conn: "REPLACE_WITH_YOUR_POSTGRES_CONNECTION_STRING"


  