apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice-dotnet
  template:
    metadata:
      labels:
        app: inventoryservice-dotnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "inventoryservice-dotnet"
        dapr.io/app-port: "8081"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
        - name: inventoryservice-dotnet
          image: localhost:5000/inventoryservice-dotnet:v1.0
          ports:
            - containerPort: 8081
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice-dotnet
spec:
  selector:
    app: inventoryservice-dotnet
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
